name: Momendum
favicon: null
layout_spectrum: 0.06565020326524973
typography_spectrum: 0.23068169434554875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.3371539479121566
  saturation: 0.40825232956558466
  rhythmicContrast: 0.6608962581958622
purpose: []
